# 크롤러 설정
# 전역 설정
global:
  days_to_crawl: 3        # 최근 3일 데이터 수집

# 스파이더별 설정
spiders:
  # DarkNetArmy : Forum 구조임
  darknet_army:
    target_url: "http://dna777qhcrxy5sbvk7rkdd2phhxbftpdtxvwibih26nr275cdazx4uyd.onion"
    endpoints:
      # 0. What's New
      whats_new: "/whats-new/posts/"
      # 1. Hacked Database Leaks
      hacked_db: "/forums/%E2%AD%90-hacked-database-leaks-%E2%AD%90.27/"
      # 2. Info Stealer Logs
      info_stealers: "/forums/%E2%AD%90-info-stealers-logs-%E2%AD%90.63/"
      # 3. Paid Accounts
      paid_accounts: "/forums/paid-accounts-login-leaks-usernames-passwords-cookies.44/"
      # 4. Combolists
      combolists: "/forums/%E2%AD%90-combolists-%E2%AD%90.25/"
    
    # 게시판별 수집 페이지 수 제한 (Endpoint Key 기준)
    boards:
      whats_new: 2
      hacked_db: 1
      info_stealers: 1
      paid_accounts: 1
      combolists: 1

  # Abyss
  abyss:
    target_url: "http://3ev4metjirohtdpshsqlkrqcmxq6zu3d7obrdhglpy5jpbr7whmlfgqd.onion/"

  bfdx:
    boards:
      "main-board": 1
