# 크롤러 설정
# 전역 설정
global:
  days_to_crawl: 14        # 최근 14일 데이터 수집, 첫 빌딩 시 권장. 이후 1일~2일 단위로 수정 후 스케쥴링 권장

# 스파이더별 설정
spiders:
  # DarkNetArmy : Forum 구조임
  darknet_army:
    target_url: "http://dna777qhcrxy5sbvk7rkdd2phhxbftpdtxvwibih26nr275cdazx4uyd.onion"
    endpoints:
      # 0. What's New
      whats_new: "/whats-new/posts/"
      # 1. Hacked Database Leaks
      hacked_db: "/forums/%E2%AD%90-hacked-database-leaks-%E2%AD%90.27/"
      # 2. Info Stealer Logs
      info_stealers: "/forums/%E2%AD%90-info-stealers-logs-%E2%AD%90.63/"
      # 3. Paid Accounts
      paid_accounts: "/forums/paid-accounts-login-leaks-usernames-passwords-cookies.44/"
      # 4. Combolists
      combolists: "/forums/%E2%AD%90-combolists-%E2%AD%90.25/"
    
    # 게시판별 수집 페이지 수 제한 (Endpoint Key 기준)
    boards:
      whats_new: 2
      hacked_db: 3
      info_stealers: 3
      paid_accounts: 3
      combolists: 3

  # Abyss
  abyss:
    target_url: "http://3ev4metjirohtdpshsqlkrqcmxq6zu3d7obrdhglpy5jpbr7whmlfgqd.onion/"

  play_news:
    target_url: "http://k7kg3jqxang3wh7hnmaiokchk7qoebupfgoik6rha6mjpzwupwtj25yd.onion/"
    endpoints:
      news: "/index.php"
    boards:
      news: 3
    default_max_pages: 5

  best_carding_world:
    target_url: "http://bestteermb42clir6ux7xm76d4jjodh3fpahjqgbddbmfrgp4skg2wqd.onion/"
    endpoints:
      hacked_db: "/viewforum.php?f=30"
      malware: "/viewforum.php?f=47"
    # 게시판별 수집 페이지 수 제한 (Endpoint Key 기준)
    boards:
      hacked_db: 3
      malware: 3
  
  bfdx:
    target_url: "http://bfdxjkv5e2z3ilrifzbnvxxvhbzsj67akjpj3zc6smzr4vv6oz565gyd.onion/"
    endpoints:
      buy_sell: "/forums/buy-sell.70/"
      worldwide_news: "/forums/worldwide-news.66/"
    
    boards:
      buy_sell: 1
      worldwide_news: 1

  rhysida:
    target_url: "http://rhysidafohrhyy2aszi7bm32tnjat5xri65fopcxkdfxhi4tidsg7cad.onion/archive.php"
  
  lockbit:
    target_url: "http://lockbit3olp7oetlc4tl5zydnoluphh7fvdt5oa6arcp2757r7xkutid.onion/"

  akira:
    target_url: "https://akiral2iz6a7qgd3ayp3l6yub7xx2uep76idk3u2kollpj5z3z636bad.onion/"
